
on:
  push:

jobs:
  yarn-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'

    - run: npm init --scope ${{ github.repository_owner }} -y

    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}    

  yarn-add:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'

    - run: echo '"@jcansdale-test:registry" "https://npm.pkg.github.com/"' > .yarnrc
      
    - run: yarn add @jcansdale-test/npm-load@1.0.1056
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
