on:
  push:
  workflow_dispatch:

env:
  version: "1.0.0-g${{ github.sha }}"
  package: "@${{ github.repository }}"
  registry_url: "https://npm.pkg.github.com"
  scope: "${{ github.repository_owner }}"

jobs:
  yarn-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v1
      with:
        registry-url: ${{ env.registry_url }}
        scope: ${{ env.scope }}

    - run: echo '"@${{ github.repository_owner }}:registry" "https://npm.pkg.github.com/"' > .yarnrc

    - run: npm init --scope ${{ env.scope }} -y

    - run: yarn version --new-version ${{ env.version }} --no-git-tag-version

    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

  yarn-add:
    needs: [yarn-publish]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v1
      with:
        registry-url: ${{ env.registry_url }}
        scope: ${{ env.scope }}
          
    - run: echo '"@${{ github.repository_owner }}:registry" "https://npm.pkg.github.com/"' > .yarnrc

    - run: yarn add ${{ env.package }}@${{ env.version }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
