
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo '"@jcansdale-test:registry" "https://npm.pkg.github.com/"' > .yarnrc
      
    - run: yarn install @jcansdale-test/npm-load@1.0.1056
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
